name: Sync GitHub Issues to Jira

on:
  issues:
    types: [opened]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Send issue to Jira
      env:
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
      run: |

        issue_title="${{ github.event.issue.title }}"
        issue_body="${{ github.event.issue.body }}"
        issue_url="${{ github.event.issue.html_url }}"
        issue_number="${{ github.event.issue.number }}"

        data=$(jq -n \
          --arg summary "$issue_title" \
          --arg description "GitHub Issue URL: [$issue_url]" \
          --arg project "IT" \
          --arg issuetype "Epic" \
          '{fields: {summary: $summary, description: $description, project: {key: $project}, issuetype: {name: $issuetype}}}')

        response=$(curl -s -o response.json -w "%{http_code}" \
          -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
          -X POST \
          -H "Content-Type: application/json" \
          --data "$data" \
          "$JIRA_URL/rest/api/2/issue/")
        cat response.json
        jira_issue_key=$(jq -r '.key' < response.json)

        echo "::set-output name=jira_issue_key::$jira_issue_key"

        echo "Jira issue created with key: $jira_issue_key"
